version: '2'

services:
  app:
    build: ../../ciao
    networks:
      - proxy_network
  
  proxy:
    build: ../../nginx-reverse-proxy
    ports:
      - 5678:8080
    networks:
      - proxy_network
    environment:
      PORT: 8080

networks:
  proxy_network:
