version: '2'

services:
  app:
    image: ciao
    networks:
      - proxy_network

  proxy:
    image: woollyams/nginx-reverse-proxy:201603101638
    ports:
      - 5678:8080
    networks:
      - proxy_network
    environment:
      PORT: 8080

networks:
  proxy_network:
